kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: standalone
resources:
  - ../base
  - ./ingress.yaml
secretGenerator:
- envs:
  - secrets.env
  name: stop-secret
configMapGenerator:
  - name: stop-e-data-config
    literals:
      - EDATA_BUILD = "Prod"
generatorOptions:
  disableNameSuffixHash: true
